name: Rom-Builder

on:
  push:
    branches: [ Test ]

jobs:
  build:
    name: Rom-Builder
    runs-on: ubuntu-latest
    if: github.actor == 'NFS86'
    steps:
    - name: Clone Script..
      uses: NFS86/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        user: medusa
        pass: ${{ secrets.PASSWORD }}
        args: "-tt"
        command: |
          my_dir="$HOME"
          mkdir -p $my_dir/script
          cd $my_dir/script
          rm -rf *
          wget https://raw.githubusercontent.com/NFS-projects/Rom-Builder/Test/script/sync.sh
          wget https://raw.githubusercontent.com/NFS-projects/Rom-Builder/Test/script/building.sh
          wget https://raw.githubusercontent.com/NFS-projects/Rom-Builder/Test/script/upload.sh
          wget https://raw.githubusercontent.com/NFS-projects/Rom-Builder/Test/script/notif.sh
          wget https://raw.githubusercontent.com/NFS-projects/Rom-Builder/Test/rosy/build_rom.sh

    - name: Sync Rom..
      uses: NFS86/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        user: medusa
        pass: ${{ secrets.PASSWORD }}
        args: "-tt"
        command: |
          bash $HOME/script/sync.sh

    - name: Building Rom..
      uses: NFS86/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        user: medusa
        pass: ${{ secrets.PASSWORD }}
        args: "-tt"
        command: |
          bash $HOME/script/building.sh

    - name: Upload Rom..
      uses: NFS86/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        user: medusa
        pass: ${{ secrets.PASSWORD }}
        command: |
          bash $HOME/script/upload.sh

    - name: Send notif..
      uses: NFS86/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        user: medusa
        pass: ${{ secrets.PASSWORD }}
        args: "-tt"
        command: |
          bash $HOME/script/notif.sh